"""DeepSeek Harness Python.

The package is intentionally split into small runtime seams.  The public
surface starts with the native Python agent core; web/API and SDK layers build
on the same Session and Agent contracts.
"""

from .agent import Agent, AgentStatus, RunResult
from .checkpoint import CheckpointCallback, SessionCheckpointPolicy
from .compaction import (
    CompactionPolicy,
    CompactionResult,
    compact_if_needed,
    estimate_message_tokens,
    estimate_messages_tokens,
)
from .errors import LlmFailure, LspError, WebError
from .llm import DeepSeekAdapter, LlmAdapter, LlmCallConfig, LlmRequest, RetryPolicy, StreamChunk
from .lsp import (
    DEFAULT_LSP_TOOL_TIMEOUT_SECONDS,
    DEFAULT_MAX_LOCATIONS,
    DEFAULT_MAX_RESULT_CHARS,
    LSP_OPERATIONS,
    LSP_PROMPT_TEXT,
    LspHover,
    LspHoverResult,
    LspLocation,
    LspLocationsResult,
    LspOperation,
    LspPosition,
    LspProvider,
    LspProviderQuery,
    LspQueryRequest,
    LspQueryResult,
    LspRange,
    LspRuntime,
    LspToolInput,
    final_extension,
    format_hover,
    format_locations,
    install_lsp_tools,
    normalize_extension,
    parse_lsp_args,
    render_uri,
)
from .lsp_stdio import (
    LspStdioProvider,
    LspStdioServerConfig,
    install_lsp_stdio_providers,
    normalize_hover,
    normalize_locations,
)
from .models import Message, TextContent, ToolCallContent, ToolResultContent
from .sdk import DeepSeekHarness, DeepSeekHarnessConfig
from .sdk import RunResult as SdkRunResult
from .sdk_process import (
    DeepSeekHarnessProcess,
    HarnessClient,
    JsonRpcResponseError,
    NotificationSubscription,
    ProcessRunResult,
    ProcessSession,
)
from .session import JsonlSessionStore, Session, SessionEvent, SessionHeader, SessionSurfaceNode
from .session_title import (
    SessionTitleConfig,
    SessionTitleInvalidError,
    SessionTitleService,
    SessionTitleSnapshot,
    fallback_session_title,
    fold_session_title,
    normalize_session_title,
    truncate_title_utf8,
)
from .session_title_llm import (
    SESSION_TITLE_TIMEOUT_CODE,
    TITLE_PROVIDER_ID,
    SessionTitleLlmConfig,
    SessionTitleLlmError,
    SessionTitleLlmResult,
    generate_session_title,
)
from .spill import (
    LocalSpillStore,
    SaveTextSpill,
    SpillOwner,
    SpillPolicy,
    SpillRef,
    SpillSource,
    SpillStore,
)
from .tool_result_pruner import (
    DEFAULT_TOOL_RESULT_PRUNE_CONFIG,
    PRUNE_MARKER,
    PrunedEntry,
    PruneResult,
    ToolResultPruneConfig,
    ToolResultPruner,
)
from .web_capability import (
    DeepSeekSearchOptions,
    DeepSeekSearchProvider,
    HttpFetchLimits,
    HttpFetchProvider,
    WebFetchBody,
    WebFetchResult,
    WebRuntime,
    WebSearchResult,
    WebSource,
    format_fetch_output,
    format_search_output,
    install_web_tools,
)

__all__ = [
    "Agent",
    "AgentStatus",
    "CheckpointCallback",
    "CompactionPolicy",
    "CompactionResult",
    "DeepSeekAdapter",
    "DeepSeekHarness",
    "DeepSeekHarnessConfig",
    "DeepSeekHarnessProcess",
    "HarnessClient",
    "JsonRpcResponseError",
    "JsonlSessionStore",
    "LlmAdapter",
    "LlmCallConfig",
    "LlmFailure",
    "LspError",
    "LspHover",
    "LspHoverResult",
    "LspLocation",
    "LspLocationsResult",
    "LspOperation",
    "LspPosition",
    "LspProvider",
    "LspProviderQuery",
    "LspQueryRequest",
    "LspQueryResult",
    "LspRange",
    "LspRuntime",
    "LspToolInput",
    "LspStdioProvider",
    "LspStdioServerConfig",
    "LlmRequest",
    "Message",
    "NotificationSubscription",
    "ProcessSession",
    "ProcessRunResult",
    "PRUNE_MARKER",
    "PruneResult",
    "PrunedEntry",
    "RunResult",
    "RetryPolicy",
    "SdkRunResult",
    "Session",
    "SessionEvent",
    "SessionHeader",
    "SessionSurfaceNode",
    "SessionCheckpointPolicy",
    "SessionTitleConfig",
    "SessionTitleInvalidError",
    "SessionTitleService",
    "SessionTitleSnapshot",
    "SessionTitleLlmConfig",
    "SessionTitleLlmError",
    "SessionTitleLlmResult",
    "LocalSpillStore",
    "SaveTextSpill",
    "SpillOwner",
    "SpillPolicy",
    "SpillRef",
    "SpillSource",
    "SpillStore",
    "StreamChunk",
    "TextContent",
    "ToolCallContent",
    "ToolResultContent",
    "ToolResultPruneConfig",
    "ToolResultPruner",
    "WebError",
    "WebFetchBody",
    "WebFetchResult",
    "WebRuntime",
    "WebSearchResult",
    "WebSource",
    "compact_if_needed",
    "estimate_message_tokens",
    "estimate_messages_tokens",
    "DeepSeekSearchOptions",
    "DeepSeekSearchProvider",
    "HttpFetchLimits",
    "HttpFetchProvider",
    "format_fetch_output",
    "format_search_output",
    "format_hover",
    "format_locations",
    "install_lsp_tools",
    "install_web_tools",
    "DEFAULT_LSP_TOOL_TIMEOUT_SECONDS",
    "DEFAULT_MAX_LOCATIONS",
    "DEFAULT_MAX_RESULT_CHARS",
    "LSP_OPERATIONS",
    "LSP_PROMPT_TEXT",
    "final_extension",
    "normalize_extension",
    "parse_lsp_args",
    "render_uri",
    "DEFAULT_TOOL_RESULT_PRUNE_CONFIG",
    "fallback_session_title",
    "fold_session_title",
    "normalize_session_title",
    "truncate_title_utf8",
    "SESSION_TITLE_TIMEOUT_CODE",
    "TITLE_PROVIDER_ID",
    "generate_session_title",
    "install_lsp_stdio_providers",
    "normalize_hover",
    "normalize_locations",
]
